---
- name: NETONE wifi user
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: 'Adding user {{ name }} {{ surname }} for NETONE wifi'
      ansible.builtin.lineinfile:
        path: /etc/dhcp/dhcpd.conf
        insertafter: '^\t#                              NETONE MDs OFFICE                            #\n'
        line: '        subclass "netone-mds" 1:device_nac_address; # {{ name }} {{ surname }} {{device_description}}'
        notify: 'Restarting services'

  handlers:
    - name: 'Restarting services'
      service:
        name: dhcpd
        state: restarted
        enabled: true