---
- name: NETONE Wi-Fi user
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: 'Adding user {{ name }} {{ surname }} for NETONE wifi - MDs OFFICE'
      ansible.builtin.lineinfile:
        path: /etc/dhcp/dhcpd.conf
        insertafter: '^\t#                              NETONE MDs OFFICE                            #\n'
        line: '        subclass "netone-mds" 1:"{{ device_nac_address }}"; # {{ name }} {{ surname }} {{device_description}}'
      notify: 'Restarting services'
      when: device_wifi_group == 'MDs Office'

    - name: 'Adding user {{ name }} {{ surname }} for NETONE wifi - FINANCE'
      ansible.builtin.lineinfile:
        path: /etc/dhcp/dhcpd.conf
        insertafter: '^\t#                              NETONE FINANCE                               #\n'
        line: '        subclass "netone-mds" 1:"{{ device_nac_address }}"; # {{ name }} {{ surname }} {{device_description}}'
      notify: 'Restarting services'
      when: device_wifi_group == 'Finance'

    - name: 'Adding user {{ name }} {{ surname }} for NETONE wifi - SALES'
      ansible.builtin.lineinfile:
        path: /etc/dhcp/dhcpd.conf
        insertafter: '^\t#                               NETONE SALES                                #\n'
        line: '        subclass "netone-mds" 1:"{{ device_nac_address }}"; # {{ name }} {{ surname }} {{device_description}}'
      notify: 'Restarting services'
      when: device_wifi_group == 'Sales'

    - name: 'Adding user {{ name }} {{ surname }} for NETONE wifi - CARTONS'
      ansible.builtin.lineinfile:
        path: /etc/dhcp/dhcpd.conf
        insertafter: '^\t#                                 NETONE CARTONS                            #\n'
        line: '        subclass "netone-mds" 1:"{{ device_nac_address }}"; # {{ name }} {{ surname }} {{device_description}}'
      notify: 'Restarting services'
      when: device_wifi_group == 'Cartons'              



  handlers:
    - name: 'Restarting services'
      service:
        name: dhcpd
        state: restarted
        enabled: true