---
- name: 4.2 - delete all powered off virtual machines from inventory and disk
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Deleting poweredoff virtual machines
      block:
        - name: Getting state of all virtual machines
          community.vmware.vmware_vm_info:
          delegate_to: localhost
          register: vm_info

        - name: Deleting all poweredoff virtual machines from inventory and disk
          community.vmware.vmware_guest:
            uuid: "{{ item.uuid }}"
            delete_from_inventory: True
            state: absent
          with_items:
            - "{{ vm_info.virtual_machines | community.general.json_query(query) }}"
          vars:
            query: "[?power_state=='poweredOff']"
          register: result