---
- name: 4.3_add_new_disk_to_a_virtual_machine
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    vm_name: "Unifi Wifi Controller 7.1"

  tasks:
    - name: Adding new disk 
      block:
        - name: Getting state of all virtual machines
          community.vmware.vmware_vm_info:
          delegate_to: localhost
          register: vm_info

        - name: Gathering vm info
          community.vmware.vmware_guest_info:
            datacenter: "{{ item.datacenter }}"
            uuid: "{{ item.uuid }}"
          with_items:
            - "{{ vm_info.virtual_machines | community.general.json_query(query) }}"
          vars:
            query: "[?guest_name=='{{ vm_name }}']"
          register: guest_info
        
        - name: Connect to VMWare and shutdown guest
          community.vmware.vmware_guest:
            datacenter: "{{ item.datacenter }}"
            name: "{{ item.guest_name }}"
            state: shutdownguest
          failed_when: vm_shutdown.instance.hw_power_status != 'poweredOff' and vm_shutdown.changed == false
          register: vm_shutdown
          with_items:
            - "{{ vm_info.virtual_machines | community.general.json_query(query) }}"
          vars:
            query: "[?guest_name=='{{ vm_name }}']"

        - name: Wait 15 seconds
          ansible.builtin.pause:
            seconds: 15

        - name: add disk to virtual machine
          vmware_guest_disk:
            datacenter: "{{ item.datacenter }}"  #"{{ vcenter_datacenter }}"
            name: "{{ item.guest_name }}" #"{{ vm_name }}"
            disk:
              - size_gb: 1 #"{{ vm_disk_size_gb }}"
                #datastore: "{{ item.datastore }}"
                type: thick #"{{ vm_disk_type }}"
                datastore: "corro-datastore2" #"{{ item.datastore }}" #"{{ vm_disk_datastore }}"
                scsi_controller: 1 #"{{ vm_disk_scsi_controller }}"
                scsi_type: paravirtual #"{{ vm_disk_scsi_type }}"
                unit_number: 1 #"{{ vm_disk_scsi_unit }}"                
                disk_mode: persistent #"{{ vm_disk_mode }}"
                state: present
          with_items:
            - "{{ vm_info.virtual_machines | community.general.json_query(query) }}"
          vars:
            query: "[?guest_name=='{{ vm_name }}']"                
          register: vm_add_disk


        - name: Connect to VMWare and poweron guest
          community.vmware.vmware_guest:
            datacenter: "{{ item.datacenter }}"
            name: "{{ item.guest_name }}"
            state: poweron
          failed_when: vm_shutdown.instance.hw_power_status != 'poweredOff' and vm_shutdown.changed == false
          register: vm_shutdown
          with_items:
            - "{{ vm_info.virtual_machines | community.general.json_query(query) }}"
          vars:
            query: "[?guest_name=='{{ vm_name }}']"
