---
- name: 4.4_increase disk space of virtual machine
  hosts: localhost
  connection: local
  gather_facts: no
  # vars:
    # vm_name: "Unifi Wifi Controller 7.1"
    # vm_disk_size_gb:
    # vm_disk_scsi_controller:
    # vm_disk_scsi_type:
    # vm_disk_scsi_unit:

  tasks:
    - name: increasing disk size disk 
      block:
        - name: Getting state of all virtual machines
          community.vmware.vmware_vm_info:
          delegate_to: localhost
          register: vm_info

        - name: Gathering vm info
          community.vmware.vmware_guest_info:
            datacenter: "{{ item.datacenter }}"
            uuid: "{{ item.uuid }}"
          with_items:
            - "{{ vm_info.virtual_machines | community.general.json_query(query) }}"
          vars:
            query: "[?guest_name=='{{ vm_name }}']"
          register: guest_info
  
        - name: shutting down guest
          community.vmware.vmware_guest_powerstate:
            datacenter: "{{ item.datacenter }}"
            name: "{{ item.guest_name }}"
            state: shutdown-guest
            state_change_timeout: 200      
          with_items:
            - "{{ vm_info.virtual_machines | community.general.json_query(query) }}"
          vars:
            query: "[?guest_name=='{{ vm_name }}']"
          failed_when: vm_shutdown.instance.hw_power_status != 'poweredOff' and vm_shutdown.changed == false        
          register: vm_shutdown    


        - name: Wait 15 seconds
          ansible.builtin.pause:
            seconds: 15

        - name: increasing virtual machine disk
          vmware_guest_disk:
            datacenter: "{{ vcenter_datacenter }}"
            name: "{{ vm_name }}"          
            # datacenter: "{{ item.datacenter }}"  #"{{ vcenter_datacenter }}"
            # name: "{{ item.guest_name }}" #"{{ vm_name }}"
            disk:
              - size_gb: "{{ vm_disk_size_gb }}"
                scsi_controller: "{{ vm_disk_scsi_controller }}"
                scsi_type: "{{ vm_disk_scsi_type }}"
                unit_number: "{{ vm_disk_scsi_unit }}"             
              # - size_gb: 3 #"{{ vm_disk_size_gb }}"
              #   scsi_controller: 1 #"{{ vm_disk_scsi_controller }}"
              #   scsi_type: paravirtual #"{{ vm_disk_scsi_type }}"
              #   unit_number: 1 #"{{ vm_disk_scsi_unit }}"                
                state: present                
          with_items:
            - "{{ vm_info.virtual_machines | community.general.json_query(query) }}"
          vars:
            query: "[?guest_name=='{{ vm_name }}']"                
          register: vm_add_disk

        - name: Wait 30 seconds
          ansible.builtin.pause:
            seconds: 30         

        - name: powering on guest
          community.vmware.vmware_guest_powerstate:
            datacenter: "{{ item.datacenter }}"
            name: "{{ item.guest_name }}"
            state: powered-on
            state_change_timeout: 200 
          with_items:
            - "{{ vm_info.virtual_machines | community.general.json_query(query) }}"
          vars:
            query: "[?guest_name=='{{ vm_name }}']"
          register: vm_poweron
          failed_when: vm_poweron.instance.hw_power_status != 'poweredOn' and vm_poweron.changed == false  

        - name: Wait 15 seconds
          ansible.builtin.pause:
            seconds: 15          