---
- name: 4.4_increase disk space of virtual machine
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    vm_name: "Unifi Wifi Controller 7.1"

  tasks:
    - name: Adding new disk 
      block:
        - name: Getting state of all virtual machines
          community.vmware.vmware_vm_info:
          delegate_to: localhost
          register: vm_info

        - name: Gathering vm info
          community.vmware.vmware_guest_info:
            datacenter: "{{ item.datacenter }}"
            uuid: "{{ item.uuid }}"
          with_items:
            - "{{ vm_info.virtual_machines | community.general.json_query(query) }}"
          vars:
            query: "[?guest_name=='{{ vm_name }}']"
          register: guest_info
  
        - name: increasing virtual machine disk
          vmware_guest_disk:
            datacenter: "{{ item.datacenter }}"  #"{{ vcenter_datacenter }}"
            name: "{{ item.guest_name }}" #"{{ vm_name }}"
            disk:
              - size_gb: 1 #"{{ vm_disk_size_gb }}"
                type: thick #"{{ vm_disk_type }}"
                datastore: "corro-datastore2" #"{{ item.datastore }}" #"{{ vm_disk_datastore }}"
                scsi_controller: 1 #"{{ vm_disk_scsi_controller }}"
                unit_number: 1 #"{{ vm_disk_scsi_unit }}"
                scsi_type: paravirtual #"{{ vm_disk_scsi_type }}"
                disk_mode: persistent #"{{ vm_disk_mode }}"
                state: present
          with_items:
            - "{{ vm_info.virtual_machines | community.general.json_query(query) }}"
          vars:
            query: "[?guest_name=='{{ vm_name }}']"                
          register: vm_add_disk