---
- name: 4.5_create_virtual_machine_from_a_template
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    vm_name: "Unifi Wifi Controller 7.1"
    vm_folder: /ha-datacenter/vm
    vm_datacenter: ha-datacenter

  tasks:
    - name: Adding new disk 
      block:
        - name: Getting state of all virtual machines
          community.vmware.vmware_vm_info:
          delegate_to: localhost
          register: vm_info

        - name: Gathering vm info
          community.vmware.vmware_guest_info:
            datacenter: "{{ item.datacenter }}"
            uuid: "{{ item.uuid }}"
          with_items:
            - "{{ vm_info.virtual_machines | community.general.json_query(query) }}"
          vars:
            query: "[?guest_name=='{{ vm_name }}']"
          failed_when: vm_shutdown.instance.hw_name == "{{ vm_name }}"
          register: vm_exists
  
        - name: vm_exists
          debug:
            var: vm_exists

        # - name: Create a VM from a template
        #   hosts: localhost
        #   connection: local
        #   gather_facts: no
        #   tasks:
        #   - name: Creating virtual machine from a template
        #     vmware_guest:
        #       name: "{{ vm_name }}"
        #       template: "{{ vm_template }}"
        #       datacenter: "ha-datacenter" #"{{ vm_datacenter }}"
        #       folder: "{{ vm_datacenter }}"
        #       state: poweredOff
            