---
- name: 4.5_create_virtual_machine_from_a_template
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    vm_name: "Unifi Wifi Controller 7.144"
    vm_template: "template_el8"
    vm_folder: /ha-datacenter/vm
    vm_datacenter: ha-datacenter

  tasks:
    - name: Adding new disk 
      block:
        - name: Getting state of all virtual machines
          community.vmware.vmware_vm_info:
          delegate_to: localhost
          register: vm_info

        - name: Gathering vm info
          community.vmware.vmware_guest_info:
            datacenter: "{{ item.datacenter }}"
            uuid: "{{ item.uuid }}"
          with_items:
            - "{{ vm_info.virtual_machines | community.general.json_query(query) }}"
          vars:
            query: "[?guest_name=='{{ vm_name }}']"
          failed_when: vm_exists.instance.hw_name == "{{ vm_name }}"
          register: vm_exists
          ignore_errors: yes
  
        - name: Checking if virtual machine name exists in the environment
          debug:
            msg: "Virtual machine {{ vm_name }} already exists with uuid {{ vm_exists.results[0].instance.hw_product_uuid }}"
            #var: vm_exists
          when: vm_exists.results[0].instance.hw_name == "{{ vm_name }}"
          failed_when: vm_exists.results[0].instance.hw_name == "{{ vm_name }}"

        # - name: Creating virtual machine from a template
        #   vmware_guest:
        #     name: "{{ vm_name }}"
        #     template: "{{ vm_template }}"
        #     datacenter: "{{ vm_datacenter }}"
        #     folder: "{{ vm_folder }}"
        #     state: poweredOff
          