---
- name: 4.7_restore_virtual_machine_from_a_snapshot
  hosts: localhost
  connection: local
  gather_facts: no
  # vars:
  #   vm_name: "Unifi Wifi Controller 7.1"
  #   vm_snapshot: "Ansible Managed Snapshot - 1668982858"
  #   vm_folder:
  #   vcenter_datacenter:

  tasks:
    - name: restoring virtual machine from snapshot
      block:
        - name: Getting state of all virtual machines
          community.vmware.vmware_vm_info:
          delegate_to: localhost
          register: vm_info

        - name: Gathering vm info
          community.vmware.vmware_guest_info:
            datacenter: "{{ item.datacenter }}"
            uuid: "{{ item.uuid }}"
          with_items:
            - "{{ vm_info.virtual_machines | community.general.json_query(query) }}"
          vars:
            query: "[?guest_name=='{{ vm_name }}']"
          register: guest_info
  
        - name: shutting down guest
          community.vmware.vmware_guest_powerstate:
            datacenter: "{{ item.datacenter }}"
            name: "{{ item.guest_name }}"
            state: shutdown-guest
            state_change_timeout: 200      
          with_items:
            - "{{ vm_info.virtual_machines | community.general.json_query(query) }}"
          vars:
            query: "[?guest_name=='{{ vm_name }}']"
          failed_when: vm_shutdown.instance.hw_power_status != 'poweredOff' and vm_shutdown.changed == false        
          register: vm_shutdown     


        - name: Wait 15 seconds
          ansible.builtin.pause:
            seconds: 15

        - name: restoring a virtual machine snapshot
          vmware_guest_snapshot:
            datacenter: "{{ vcenter_datacenter }}"
            name: "{{ vm_name }}"
            state: revert
            snapshot_name: "{{ vm_snapshot }}"
            folder: "{{ vm_folder }}"          
            # datacenter: "{{ item.datacenter }}" # "{{ vcenter_datacenter }}"
            # name: "{{ item.guest_name }}"
            # state: revert
            # snapshot_name: "{{ vm_snapshot }}"
            # folder: "{{ item.folder }}"
          with_items:
            - "{{ vm_info.virtual_machines | community.general.json_query(query) }}"
          vars:
            query: "[?guest_name=='{{ vm_name }}']"                
          register: vm_snapshot

        - name: Wait 20 seconds
          ansible.builtin.pause:
            seconds: 20          

        - name: powering on guest
          community.vmware.vmware_guest_powerstate:
            datacenter: "{{ item.datacenter }}"
            name: "{{ item.guest_name }}"
            state: powered-on
            state_change_timeout: 200 
          with_items:
            - "{{ vm_info.virtual_machines | community.general.json_query(query) }}"
          vars:
            query: "[?guest_name=='{{ vm_name }}']"
          register: vm_poweron
          failed_when: vm_poweron.instance.hw_power_status != 'poweredOn' and vm_poweron.changed == false  

        - name: Wait 15 seconds
          ansible.builtin.pause:
            seconds: 15          