---
- name: 5.2 - RHEL - clear non-relevant log files in /var
  hosts: "{{ search_hosts }}"
  gather_facts: true

  # vars:
  #   search_hosts:
  #   find_patterns_list

  tasks:
    - name: Check reachability
      ping:
      register: reachability
    - name: Finding and deleting files
      block:
        - name: Finding files for deletion
          find:
            paths: /var # "{{ find_paths_list }}"
            patterns: "{{ find_patterns_list }}"
            use:regex: true
          register: find_results

        - name: Listing files to be deleted.
          debug:
            var: find_results.files

        - name: deleting files from find results
          file:
            path: "{{ item.path }}"
            state: absent
          with_items: "{{ find_results.files }}"
      when: "'success' in reachability.stdout"

