---
- name: 5.2 - RHEL - clear non-relevant log files in /var
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Check reachability
      ping:
      register: reachability
    - name: Finding and deleting files
      block:
        - name: Finding files for deletion
          find:
            paths: "{{ path_to_search.split('\n') }}"
            patterns: "{{ find_patterns_list.split('\n') }}"
            hidden: true
            file_type: any
            recurse: true
          register: find_results

        - name: Listing files to be deleted.
          debug:
            var: find_results.files

        - name: deleting files from find results
          file:
            path: "{{ item.path }}"
            state: absent
          with_items: "{{ find_results.files }}"

