---
- name: 5.8 - create and configure Samba Share
  hosts: all
  gather_facts: yes
  become: true
  # vars:
  #   smb_guest_allowed:
  #   smb_share_comment:
  #   smb_share_directory_path:
  #   smb_share_group:
  #   smb_share_owner:
  #   smb_share_read_only:
  #   smb_share_write_list:
  #   smb_valid_users:

  tasks:
    - name: Check Samba Packages are present
      ansible.builtin.yum:
        name: 
          - cifs-utils
          - samba-client
          - policycoreutils-python-utils
        state: present

    - name: Start and enable samba service
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
        - "smb"
        - "nmb"
        
    - name: Ensure SELinux is enabled and enforcing
      ansible.posix.selinux:
        policy: targeted
        state: enforcing

    - name: Ensure samba share exists.
      file:
        path: "{{ smb_share_directory_path }}"
        state: directory
        owner: "{{ smb_share_owner }}"
        group: "{{ smb_share_group }}"
        mode: 0777

    - name: Set selinux context for "{{ smb_share_directory_path }}" to samba_share_t
      community.general.sefcontext:
        target: "{{ smb_share_directory_path }}"
        setype: samba_share_t
        state: present

    # - name: Configure samba share
    #   ansible.builtin.blockinfile:
    #     path: /etc/smb.conf
    #     marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    #     block: |

    #     ["{{ samba_share_name }}"]
    #       comment = {{ smb_share_comment }}
    #       path = {{ samba_share_directory_path }}
    #       guest ok = {{ smb_guest_allowed }}
    #       read only =  {{ smb_share_read_only }}
    #       valid users = {{ smb_valid_users }}
    #       write list = {{ smb_share_write_list }}

    - name: Updating firewall rules to allow Samba traffic
      firewalld:
        permanent: yes
        immediate: yes
        service: "{{ item }}"
        state: enabled
      with_items:
        - samba
        - samba-client

    - name: validating samba configuration
      shell: smbclient -L localhost -U "{{ smb_share_owner }}"
      #delegate_to: inventory_hostname