---
#################################################
- name: Install java for WebLogic servers
  hosts: "{{ java_tar_src }}"
  gather_facts: yes

  vars:
    JAVA_HOME: usr/app/jdk1.8.0.241
    JRE_HOME: "{{ JAVA_HOME }}/jre"

  environment:
    JAVA_HOME: usr/app/jdk1.8.0.241
    JRE_HOME: "{{ JAVA_HOME }}/jre"
    PATH: "{{ ansible_env.PATH }}:{{ $JAVA_HOME }}/bin:{{ JRE_HOME }}"

  tasks:
    - name: getting java file from remote host
      fetch:
        src: //example.com/path/java.tar
        dest: files/
        owner: app
        group: app
        mode: 0775

####################################################
- name: Install java for WebLogic servers
  hosts: all
  gather_facts: yes

  vars:
    JAVA_HOME: usr/app/jdk1.8.0.241
    JRE_HOME: "{{ JAVA_HOME }}/jre"

  environment:
    JAVA_HOME: usr/app/jdk1.8.0.241
    JRE_HOME: "{{ JAVA_HOME }}/jre"
    PATH: "{{ ansible_env.PATH }}:{{ $JAVA_HOME }}/bin:{{ JRE_HOME }}"

  tasks:
    - name: ensure group called app exists
      group:
        name: app

    - name: ensure user called app with group app exists
      user:
        name: app
        group: app

    - name: ensure /usr/app directory exists
      file:
        path: files
        state: directory
        owner: app
        group: app
        mode: 0775

    - name: ensure /usr/app directory exists
      file:
        path: /usr/app
        state: directory
        owner: app
        group: app
        mode: 0775

    - name: Copying java archive to local device
      copy:
        src: files/java.tar
        dest: /usr/app
        owner: app
        group: app
        mode: 0775

    - name: Unpacking java.tar file in /usr/app
      unarchive:
        src: /usr/app/java.tar
        dest: /usr/app
        owner: app
        group: app
        mode: 0775

    - name: installing java
      shell:
        - alternatives --install /usr/bin/java java {{ JAVA_HOME }}/bin/java 2
        - alternatives --install /usr/bin/java java {{ JAVA_HOME }}/bin/jar 2
        - alternatives --install /usr/bin/java java {{ JAVA_HOME }}/bin/javac 2
        - alternatives --set jar {{ JAVA_HOME }}/bin/jar 2
        - alternatives --set javac {{ JAVA_HOME }}/bin/javac 2
        - alternatives --config java

    - name: Changing home directory for user app to "{{ JRE_HOME }}"
      user:
        name: "app"
        home: "{{ JRE_HOME }}"
