---
- name: Install java for WebLogic servers
  hosts: all
  gather_facts: yes

  environment:
    JAVA_HOME: usr/app/jdk1.8.0.241
    PATH: $PATH:$JAVA_HOME/bin

  tasks:
    - name: Copying java archive to local device
      copy:
    
    - name: installing java