---
- name: start/stop/restart windows services
  hosts: all
  gather_facts: false
  become: false

  tasks:
    - name: get list all all services on the host
      win_shell: Get-Service | Sort-Object Status - Descending
      register: win_svc_list

    - name: restarting windows service "{{ service_name }}"
      win_service:
        name: "{{ service_name }}"
        state: "{{ service_action }}"
      when: service_name in win_svc_list

    - debug:
      mgs: "The service {{ service_name }} was not found"
      when: service_name not in win_svc_list









