---
- name: 8.1 - SWIG stop, switch and restart gateway
  hosts: all
  gather_facts: true

  tasks:
    - name: Check host reachability
      ping:
      register: reachability

    - name: starting gateway switching process
      block:

        - name: stop ucp gateway service
          service:
            name: swig-gateway
            state: stopped
            enabled: true

        # - name: create config directory for testing
        #   file:
        #     path: /opt/{{ cluster }}
        #     state: directory

        # - name: create config files for testing
        #   file:
        #     path: /opt/{{ cluster }}/{{ item }}
        #     state: touch
        #   with_items:
        #     - switch.properties
        #     - switch.properties-acdc
        #     - switch.properties-ladc

        - name: switching UCP gateway in use
          copy:
            src: /opt/{{ cluster }}/{{ gateway }}
            dest: /opt/{{ cluster }}/switch.properties
            remote_src: true
            owner: appuser
            group: appuser
        
        - name: starting ucp gateway service
          service:
            name: swig.gateway
            state: started
            enabled: true